### ISSUE TITLE
difference between repos version and github version

### ISSUE THREAD

**Issue by FlorianJ0** [MASILab/pyPheWAS#8]
Hi,
I am working with pyPheWAS but I cannot reproduce results between the version installed via pip and the latest on github. I am using the same phenotype and genotypes files as well as call arguments. For example ;
`pip
PheWAS Code,PheWAS Name,"""-log(p)""",p-val,beta,Conf-interval beta,std_error,category_string,ICD-9,ICD-10
401.21,Hypertensive heart disease,26.499601507747713,3.1651805785946717e-27,-1.9662259011560397,"[-2.3227988245812585,-1.6096529777308208]",0.18192830390651082,circulatory system,402/402.0/402.00/402.01/402.1/402.10/402.11/402.9/402.90/402.91,I11/I11.0/I11.9
`

and 

`github
PheWAS Code,PheWAS Name,note,"""-log(p)""",p-val,beta,Conf-interval beta,std_error,category_string,ICD-9,ICD-10
401.21,Hypertensive heart disease,"[QC check did not pass for 1 out of 3 parameters Try increasing solver accuracy or number of iterations, decreasing alpha, or switch solvers]",0.4229154709307231,0.37764568698256085,0.15726474684850356,"[-0.1921099909224589,0.506639484619466]",0.17825569272026723,circulatory system,402/402.0/402.00/402.01/402.1/402.10/402.11/402.9/402.90/402.91,I11/I11.0/I11.9
`
The command I used : `pyPhewasPipeline --reg_type="log" --phenotype="pheno.csv" --group="group.csv" --response="ADKresponse" --covariates="sex"`

Also, the latest github version needs at least one covariate to run.
Thank you !

**Comment by clineci** [comment]
Thanks for bringing this up! The pypi version and the github version should be in sync now - update to version 4.2.0. 

The two versions were most likely producing different results because the default regression equation changed (so the pip-installed version was using the old equation while the github version was using the new one). See the [docs](https://pyphewas.readthedocs.io/en/latest/phewas_tools.html#pyphewasmodel) for notes on this change.

Version 4.2 also has a fix so that you should now be able to run an experiment without covariates.
